Add output visualization functions
Dynamo-HIA/hiaR pull request #36
Opened 2024-12-18 15:56 UTC by maltelueken

Adds plotting functions:

- Plot population pyramid
- Plot life expectancy
- Plot time series

They imitate the plots from the old Java GUI.

2024-12-19 15:42 UTC, f-hafner commented
for my review, important: check the Rmd file. fix the problem with github: need env variable GITHUB_PAT.

2024-12-19 16:38 UTC, maltelueken commented
I made the GITHUB_PAT optional now, so it should work without setting the environment variable.

2025-01-06 09:42 UTC, f-hafner commented on vignettes/hiaR.Rmd
> +  github_pat = Sys.getenv("GITHUB_PAT")
I had to remove the last argument to make the function call work.

2025-01-06 09:53 UTC, f-hafner commented on R/utils.R
> +                                    release_tag = "v3.0.0-beta.1",
If possible, I would try to avoid hard-coding the release name here. depending on how frequently we expect new releases of HIA, we could (i) mention this explicitly somewhere in the developer documentation and/or (ii) store the variable explicitly somewhere in a "globals" file (as an env variable), or alternatively (iii) automatically get the name of the latest release from github?

2025-01-06 09:56 UTC, f-hafner commented on vignettes/hiaR.Rmd
my `knit` call breaks here with this message:
```
Warning: setting stdout = TRUEError in run_dynamo_hia(batch_file_name, fs::path(temp_dir, Sys.getenv("DYNAMO_HIA_PATH"))) : 
  2025-01-06 10:54:55,745 DEBUG [nl.rivm.emi.dynamo.global.CommandLineSchemaFileProviderImpl] - <Instantiating : CommandLineSchemaFileProviderImpl>2025-01-06 10:54:55,745 DEBUG [nl.rivm.emi.dynamo.global.CommandLineSchemaFileProviderImpl] - <Schema location : /tmp/Rtmpcc08fA/file3e4a34d25ebaa/schemas/>Started, arguments: simulation_names.txt, 2025-01-06 10:54:55,776 DEBUG [org.apache.commons.configuration.ConfigurationUtils] - <ConfigurationUtils.locate(): base is null, name is /tmp/Rtmpcc08fA/file3e4a34d25ebaa/Simulations/Netherlands_Smoking_Intervention/configuration.xml>2025-01-06 10:54:55,776 DEBUG [org.apache.commons.configuration.ConfigurationUtils] - <Loading configuration from the absolute path /tmp/Rtmpcc08fA/file3e4a34d25ebaa/Simulations/Netherlands_Smoking_Intervention/configuration.xml>2025-01-06 10:54:55,779 DEBUG [org.apache.commons.configuration.XMLConfigurationToo] - <getting document builder for org.apache.commons.configuration.HierarchicalConfiguration$Node@258
```

2025-01-06 09:59 UTC, f-hafner requested changes
See my comments; I cannot knit. If it's easier, we can debug together and I look at the rest of the vignette when it works

2025-01-06 12:37 UTC, maltelueken commented on R/utils.R
> +                                    release_tag = "v3.0.0-beta.1",
Hmm, if we require an env variable, this makes it more complicated for the user (especially nontechnical ones). The problem with using the latest release is that the function with the default values is not reproducible anymore, i.e., it might give different results at different times after a new release was made. I will mention it in the developer documentation.

2025-01-06 13:33 UTC, f-hafner commented on R/utils.R
> +                                    release_tag = "v3.0.0-beta.1",
ok!

2025-01-06 13:39 UTC, maltelueken commented on vignettes/hiaR.Rmd
I tried to fix this but I don't think it worked. I think the issue lies within DYNAMO-HIA itself because it runs on Windows without issues, but I will investigate.

2025-01-07 10:28 UTC, maltelueken commented
Addressed your points and fixed the tests. The MacOS action is sometimes failing because of API access limiting, but it has passed for previous commits.

2025-01-07 11:01 UTC, f-hafner commented on README.Rmd
> +#### Before Making a Release
this refers to a release of the HIA program, not the hiaR package, right? -> I would make this specific about for which software a release is made.

2025-01-07 12:00 UTC, merged